<?php
/******************************************
zh_TW
Admin Category Language
******************************************/

$lang['categories'] ='類別';
$lang['error_must_select'] ='您必須選擇一個類別來組織';
$lang['error_not_found'] ='找不到請求的類別。';
$lang['syste_category'] ='組織"％s"類別';
$lang['organiz'] ='組織';
$lang['category_id'] ='ID';
$lang['category_form'] ='類別表格';
$lang['name'] ='名稱';
$lang['slug'] ='SLUG';
$lang['description'] ='描述';
$lang['excerpt'] ='摘錄';
$lang['sequence'] ='序列';
$lang['image'] ='圖片';
$lang['seo_title'] ='SEO標題';
$lang['meta'] ='元數據';
$lang['message_category_saved'] ='類別已保存！';
$lang['error_file_upload'] ='<p>您沒有選擇要上傳的文件。</ p>';
//important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category'] ='類別已被刪除。';
$lang['current_file'] ='當前文件';
$lang['confirm_delete_category'] ='你確定要刪除這個類別嗎？';
$lang['add_new_category'] ='添加新類別';
$lang['top_level_category'] ='頂級分類';
$lang['no_categories'] ='目前沒有分類';
$lang['attributes'] ='屬性';
$lang['seo'] ='SEO';
$lang['parent'] ='父母';
$lang['meta_data_description'] ='前。 ＆lt; meta name ="description" content ="我們銷售幫助您的產品"/＆gt;';
$lang['drag_and_drop'] ='拖放產品的順序，你希望他們出現。';
$lang['sku'] ='SKU';
$lang['price'] ='價格';
$lang['sale'] ='出售';
$lang['max_file_size'] ='最大文件大小';